# Generated by Django 3.2.4 on 2021-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fb', models.CharField(max_length=200)),
                ('insta', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=30, null=True, unique=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile/')),
            ],
        ),
    ]
