# Generated by Django 3.2.4 on 2021-06-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
