# Generated by Django 3.2.4 on 2021-06-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210621_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='profile/default_pic.png', null=True, upload_to='profile/'),
        ),
    ]
