# Generated by Django 3.2.4 on 2021-06-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210623_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='forget_password_token',
        ),
    ]
