# Generated by Django 3.2.4 on 2021-06-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_users_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
